用**series**生成对象的时候，pandas会自动生成一个index，默认从0开始，如果需要自定义index，可以自己指定。

In [4]:
# 导入包
import pandas as pd
import numpy as np

# 生成对象不指定index
data_1 = pd.Series(['ys', 7, 18])
data_1

0    ys
1     7
2    18
dtype: object

In [5]:
# 生成对象指定index
data_2 = pd.Series(['ys', 7, 18], 
                   index=['a', 'b', 'c'])
data_2

a    ys
b     7
c    18
dtype: object

In [7]:
# 指定列的名称
data_3 = pd.Series(['ys', 7, 18], 
                   index=['a', 'b', 'c'], 
                   name='杨赛')
data_3

a    ys
b     7
c    18
Name: 杨赛, dtype: object

In [2]:
# 如果是多列呢？
data_4 = pd.Series([['ys', 7, 18],
                    [1,2,4],
                    [9,5,7],
                    name = ['test1','test2','test3'],
                    index = ['a', 'b', 'c']]
                   )

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3929678992.py, line 5)

这个时候我们会发现，该片段代码无法运行，因为*Series*只适用于一维数组，如果要进行多维的操作，那么需要用到*DataFrame*属性。

In [5]:
data_4 = pd.DataFrame([['ys', 7, 18],
                       [1,2,4],
                       [9,5,7]],
                      columns = ['test1', 'test2', 'test3'],
                      index = ['a', 'b', 'c'])
data_4

test1  test2  test3
a    ys      7     18
b     1      2      4
c     9      5      7

In [16]:
import numpy as np

# 调用生成一个10*3的数组
num1 = np.arange(10,100,3).reshape(10,3)
print(num1)

name1 = ['a','b','c']
index1 = np.arange(10)

col1 = pd.DataFrame(num1, index=index1, columns=name1)
col1

[[10 13 16]
 [19 22 25]
 [28 31 34]
 [37 40 43]
 [46 49 52]
 [55 58 61]
 [64 67 70]
 [73 76 79]
 [82 85 88]
 [91 94 97]]


a   b   c
0  10  13  16
1  19  22  25
2  28  31  34
3  37  40  43
4  46  49  52
5  55  58  61
6  64  67  70
7  73  76  79
8  82  85  88
9  91  94  97